// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnKA1bCselw3uOOzz5DifLQ7o8dpUK-HQ',
    appId: '1:773711910836:web:783606a6238bdc9bc684e1',
    messagingSenderId: '773711910836',
    projectId: 'meydan-c3584',
    authDomain: 'meydan-c3584.firebaseapp.com',
    storageBucket: 'meydan-c3584.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSK1IWxkCF9FGHiwFc0Xel9OJHchN2z2o',
    appId: '1:773711910836:android:cbef546263f6b984c684e1',
    messagingSenderId: '773711910836',
    projectId: 'meydan-c3584',
    storageBucket: 'meydan-c3584.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfX2DZBwwEyWpNnihCCST9Ug62sXNIOVs',
    appId: '1:773711910836:ios:9707606be7f72c11c684e1',
    messagingSenderId: '773711910836',
    projectId: 'meydan-c3584',
    storageBucket: 'meydan-c3584.firebasestorage.app',
    iosBundleId: 'com.example.sosyalAg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfX2DZBwwEyWpNnihCCST9Ug62sXNIOVs',
    appId: '1:773711910836:ios:9707606be7f72c11c684e1',
    messagingSenderId: '773711910836',
    projectId: 'meydan-c3584',
    storageBucket: 'meydan-c3584.firebasestorage.app',
    iosBundleId: 'com.example.sosyalAg',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnKA1bCselw3uOOzz5DifLQ7o8dpUK-HQ',
    appId: '1:773711910836:web:0ce03b95274fa2c5c684e1',
    messagingSenderId: '773711910836',
    projectId: 'meydan-c3584',
    authDomain: 'meydan-c3584.firebaseapp.com',
    storageBucket: 'meydan-c3584.firebasestorage.app',
  );
}
